[package]
name = "assert_hex"
version = "0.4.1"
authors = ["wcampbell"]
edition = "2018"
repository = "https://github.com/wcampbell0x2a/assert_hex"
description = "display assert panics in hexadecimal {:#x?} format"
license = "MIT"
rust-version = "1.39.0"

[dependencies]
